int _isupper(int c);
int mul(int a, int b);
void print_most_numbers(void);
int _putchar(char c);
void more_numbers(void);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
void _puts(char *str);
void print_rev(char *s);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
